2023-11-03 14:45:37,545:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-03 14:45:37,545:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-03 14:45:37,545:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-03 14:45:37,545:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-03 14:47:05,944:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-03 14:47:05,945:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-03 14:47:05,945:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-03 14:47:05,945:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-03 14:47:37,124:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-03 14:47:37,125:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-03 14:47:37,125:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-03 14:47:37,125:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-03 15:01:54,323:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-03 15:01:54,324:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-03 15:01:54,324:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-03 15:01:54,324:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-03 15:04:17,853:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-03 15:04:17,854:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-03 15:04:17,854:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-03 15:04:17,854:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-03 15:17:56,533:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-03 15:17:56,533:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-03 15:17:56,533:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-03 15:17:56,534:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-03 15:17:57,666:INFO:PyCaret ClassificationExperiment
2023-11-03 15:17:57,667:INFO:Logging name: clf-default-name
2023-11-03 15:17:57,667:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2023-11-03 15:17:57,667:INFO:version 3.1.0
2023-11-03 15:17:57,667:INFO:Initializing setup()
2023-11-03 15:17:57,667:INFO:self.USI: 7017
2023-11-03 15:17:57,667:INFO:self._variable_keys: {'log_plots_param', 'fold_generator', 'X', 'exp_id', 'y', 'y_train', 'data', 'seed', 'X_test', 'memory', 'n_jobs_param', 'gpu_n_jobs_param', 'fold_groups_param', 'pipeline', 'exp_name_log', 'html_param', 'target_param', 'idx', 'fold_shuffle_param', '_ml_usecase', 'gpu_param', 'fix_imbalance', 'USI', 'y_test', 'X_train', '_available_plots', 'is_multiclass', 'logging_param'}
2023-11-03 15:17:57,667:INFO:Checking environment
2023-11-03 15:17:57,667:INFO:python_version: 3.10.8
2023-11-03 15:17:57,667:INFO:python_build: ('tags/v3.10.8:aaaf517', 'Oct 11 2022 16:50:30')
2023-11-03 15:17:57,667:INFO:machine: AMD64
2023-11-03 15:17:57,684:INFO:platform: Windows-10-10.0.22621-SP0
2023-11-03 15:17:57,688:INFO:Memory: svmem(total=12639526912, available=846163968, percent=93.3, used=11793362944, free=846163968)
2023-11-03 15:17:57,688:INFO:Physical Core: 4
2023-11-03 15:17:57,688:INFO:Logical Core: 8
2023-11-03 15:17:57,688:INFO:Checking libraries
2023-11-03 15:17:57,688:INFO:System:
2023-11-03 15:17:57,688:INFO:    python: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
2023-11-03 15:17:57,688:INFO:executable: C:\Users\duart\AppData\Local\Programs\Python\Python310\python.exe
2023-11-03 15:17:57,688:INFO:   machine: Windows-10-10.0.22621-SP0
2023-11-03 15:17:57,688:INFO:PyCaret required dependencies:
2023-11-03 15:17:57,768:INFO:                 pip: 23.3.1
2023-11-03 15:17:57,769:INFO:          setuptools: 63.2.0
2023-11-03 15:17:57,769:INFO:             pycaret: 3.1.0
2023-11-03 15:17:57,769:INFO:             IPython: 8.10.0
2023-11-03 15:17:57,769:INFO:          ipywidgets: 8.0.6
2023-11-03 15:17:57,769:INFO:                tqdm: 4.65.0
2023-11-03 15:17:57,769:INFO:               numpy: 1.23.5
2023-11-03 15:17:57,769:INFO:              pandas: 1.5.3
2023-11-03 15:17:57,769:INFO:              jinja2: 3.1.2
2023-11-03 15:17:57,769:INFO:               scipy: 1.10.1
2023-11-03 15:17:57,769:INFO:              joblib: 1.2.0
2023-11-03 15:17:57,769:INFO:             sklearn: 1.2.1
2023-11-03 15:17:57,769:INFO:                pyod: 1.1.1
2023-11-03 15:17:57,769:INFO:            imblearn: 0.11.0
2023-11-03 15:17:57,769:INFO:   category_encoders: 2.6.3
2023-11-03 15:17:57,769:INFO:            lightgbm: 4.1.0
2023-11-03 15:17:57,769:INFO:               numba: 0.58.1
2023-11-03 15:17:57,769:INFO:            requests: 2.28.1
2023-11-03 15:17:57,769:INFO:          matplotlib: 3.8.0
2023-11-03 15:17:57,769:INFO:          scikitplot: 0.3.7
2023-11-03 15:17:57,769:INFO:         yellowbrick: 1.5
2023-11-03 15:17:57,769:INFO:              plotly: 5.18.0
2023-11-03 15:17:57,769:INFO:    plotly-resampler: Not installed
2023-11-03 15:17:57,769:INFO:             kaleido: 0.2.1
2023-11-03 15:17:57,769:INFO:           schemdraw: 0.15
2023-11-03 15:17:57,769:INFO:         statsmodels: 0.14.0
2023-11-03 15:17:57,769:INFO:              sktime: 0.21.1
2023-11-03 15:17:57,769:INFO:               tbats: 1.1.3
2023-11-03 15:17:57,769:INFO:            pmdarima: 2.0.4
2023-11-03 15:17:57,769:INFO:              psutil: 5.9.4
2023-11-03 15:17:57,769:INFO:          markupsafe: 2.1.1
2023-11-03 15:17:57,769:INFO:             pickle5: Not installed
2023-11-03 15:17:57,769:INFO:         cloudpickle: 3.0.0
2023-11-03 15:17:57,769:INFO:         deprecation: 2.1.0
2023-11-03 15:17:57,769:INFO:              xxhash: 3.4.1
2023-11-03 15:17:57,769:INFO:           wurlitzer: Not installed
2023-11-03 15:17:57,769:INFO:PyCaret optional dependencies:
2023-11-03 15:17:57,783:INFO:                shap: Not installed
2023-11-03 15:17:57,783:INFO:           interpret: Not installed
2023-11-03 15:17:57,783:INFO:                umap: Not installed
2023-11-03 15:17:57,783:INFO:     ydata_profiling: Not installed
2023-11-03 15:17:57,783:INFO:  explainerdashboard: Not installed
2023-11-03 15:17:57,783:INFO:             autoviz: Not installed
2023-11-03 15:17:57,783:INFO:           fairlearn: Not installed
2023-11-03 15:17:57,783:INFO:          deepchecks: Not installed
2023-11-03 15:17:57,783:INFO:             xgboost: Not installed
2023-11-03 15:17:57,783:INFO:            catboost: Not installed
2023-11-03 15:17:57,783:INFO:              kmodes: Not installed
2023-11-03 15:17:57,783:INFO:             mlxtend: Not installed
2023-11-03 15:17:57,783:INFO:       statsforecast: Not installed
2023-11-03 15:17:57,783:INFO:        tune_sklearn: Not installed
2023-11-03 15:17:57,783:INFO:                 ray: Not installed
2023-11-03 15:17:57,783:INFO:            hyperopt: Not installed
2023-11-03 15:17:57,783:INFO:              optuna: Not installed
2023-11-03 15:17:57,783:INFO:               skopt: Not installed
2023-11-03 15:17:57,783:INFO:              mlflow: Not installed
2023-11-03 15:17:57,783:INFO:              gradio: Not installed
2023-11-03 15:17:57,784:INFO:             fastapi: Not installed
2023-11-03 15:17:57,784:INFO:             uvicorn: Not installed
2023-11-03 15:17:57,784:INFO:              m2cgen: Not installed
2023-11-03 15:17:57,784:INFO:           evidently: Not installed
2023-11-03 15:17:57,784:INFO:               fugue: Not installed
2023-11-03 15:17:57,784:INFO:           streamlit: Not installed
2023-11-03 15:17:57,784:INFO:             prophet: Not installed
2023-11-03 15:17:57,784:INFO:None
2023-11-03 15:17:57,784:INFO:Set up data.
2023-11-03 15:17:57,802:INFO:Set up folding strategy.
2023-11-03 15:17:57,802:INFO:Set up train/test split.
2023-11-03 15:17:57,813:INFO:Set up index.
2023-11-03 15:17:57,814:INFO:Assigning column types.
2023-11-03 15:17:57,817:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2023-11-03 15:17:57,854:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-11-03 15:17:57,858:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-11-03 15:17:57,890:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-03 15:17:57,891:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-03 15:17:57,926:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-11-03 15:17:57,927:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-11-03 15:17:57,952:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-03 15:17:57,953:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-03 15:17:57,953:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2023-11-03 15:17:57,988:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-11-03 15:17:58,009:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-03 15:17:58,009:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-03 15:17:58,046:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-11-03 15:17:58,068:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-03 15:17:58,068:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-03 15:17:58,068:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2023-11-03 15:17:58,122:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-03 15:17:58,122:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-03 15:17:58,180:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-03 15:17:58,180:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-03 15:17:58,192:INFO:Preparing preprocessing pipeline...
2023-11-03 15:17:58,194:INFO:Set up label encoding.
2023-11-03 15:17:58,194:INFO:Set up simple imputation.
2023-11-03 15:17:58,196:INFO:Set up encoding of ordinal features.
2023-11-03 15:17:58,200:INFO:Set up encoding of categorical features.
2023-11-03 15:17:58,200:INFO:Set up feature normalization.
2023-11-03 15:17:58,324:INFO:Finished creating preprocessing pipeline.
2023-11-03 15:17:58,352:INFO:Pipeline: Pipeline(memory=FastMemory(location=C:\Users\duart\AppData\Local\Temp\joblib),
         steps=[('label_encoding',
                 TransformerWrapperWithInverse(exclude=None, include=None,
                                               transformer=LabelEncoder())),
                ('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['year', 'divID', 'rank', 'seeded',
                                             'o_fgm', 'o_fga', 'o_ftm', 'o_fta',
                                             'o_3pm', 'o_3pa', 'o_oreb',
                                             'o_dreb', 'o_...
                                    include=['lgID', 'tmID', 'franchID',
                                             'name'],
                                    transformer=OneHotEncoder(cols=['lgID',
                                                                    'tmID',
                                                                    'franchID',
                                                                    'name'],
                                                              drop_invariant=False,
                                                              handle_missing='return_nan',
                                                              handle_unknown='value',
                                                              return_df=True,
                                                              use_cat_names=True,
                                                              verbose=0))),
                ('normalize',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=StandardScaler(copy=True,
                                                               with_mean=True,
                                                               with_std=True)))],
         verbose=False)
2023-11-03 15:17:58,352:INFO:Creating final display dataframe.
2023-11-03 15:17:58,635:INFO:Setup _display_container:                     Description             Value
0                    Session id               123
1                        Target           playoff
2                   Target type            Binary
3                Target mapping        N: 0, Y: 1
4           Original data shape         (142, 50)
5        Transformed data shape        (142, 104)
6   Transformed train set shape         (99, 104)
7    Transformed test set shape         (43, 104)
8              Ordinal features                 4
9              Numeric features                41
10         Categorical features                 8
11     Rows with missing values            100.0%
12                   Preprocess              True
13              Imputation type            simple
14           Numeric imputation              mean
15       Categorical imputation              mode
16     Maximum one-hot encoding                25
17              Encoding method              None
18                    Normalize              True
19             Normalize method            zscore
20               Fold Generator   StratifiedKFold
21                  Fold Number                10
22                     CPU Jobs                -1
23                      Use GPU             False
24               Log Experiment             False
25              Experiment Name  clf-default-name
26                          USI              7017
2023-11-03 15:17:58,698:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-03 15:17:58,699:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-03 15:17:58,756:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-03 15:17:58,756:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-03 15:17:58,757:INFO:setup() successfully completed in 1.09s...............
2023-11-03 15:17:58,757:INFO:Initializing compare_models()
2023-11-03 15:17:58,757:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001EF58621690>, include=None, fold=None, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x000001EF58621690>, 'include': None, 'exclude': None, 'fold': None, 'round': 4, 'cross_validation': True, 'sort': 'Accuracy', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>}, exclude=None)
2023-11-03 15:17:58,757:INFO:Checking exceptions
2023-11-03 15:17:58,759:INFO:Preparing display monitor
2023-11-03 15:17:58,764:INFO:Initializing Logistic Regression
2023-11-03 15:17:58,764:INFO:Total runtime is 0.0 minutes
2023-11-03 15:17:58,764:INFO:SubProcess create_model() called ==================================
2023-11-03 15:17:58,765:INFO:Initializing create_model()
2023-11-03 15:17:58,765:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001EF58621690>, estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001EF588AD300>, model_only=True, return_train_score=False, kwargs={})
2023-11-03 15:17:58,765:INFO:Checking exceptions
2023-11-03 15:17:58,765:INFO:Importing libraries
2023-11-03 15:17:58,765:INFO:Copying training dataset
2023-11-03 15:17:58,768:INFO:Defining folds
2023-11-03 15:17:58,768:INFO:Declaring metric variables
2023-11-03 15:17:58,768:INFO:Importing untrained model
2023-11-03 15:17:58,768:INFO:Logistic Regression Imported successfully
2023-11-03 15:17:58,768:INFO:Starting cross validation
2023-11-03 15:17:58,770:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-03 15:18:05,907:INFO:Calculating mean and std
2023-11-03 15:18:05,908:INFO:Creating metrics dataframe
2023-11-03 15:18:05,912:INFO:Uploading results into container
2023-11-03 15:18:05,913:INFO:Uploading model into container now
2023-11-03 15:18:05,914:INFO:_master_model_container: 1
2023-11-03 15:18:05,914:INFO:_display_container: 2
2023-11-03 15:18:05,914:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-11-03 15:18:05,914:INFO:create_model() successfully completed......................................
2023-11-03 15:18:05,980:INFO:SubProcess create_model() end ==================================
2023-11-03 15:18:05,980:INFO:Creating metrics dataframe
2023-11-03 15:18:05,983:INFO:Initializing K Neighbors Classifier
2023-11-03 15:18:05,983:INFO:Total runtime is 0.12030678987503052 minutes
2023-11-03 15:18:05,983:INFO:SubProcess create_model() called ==================================
2023-11-03 15:18:05,983:INFO:Initializing create_model()
2023-11-03 15:18:05,983:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001EF58621690>, estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001EF588AD300>, model_only=True, return_train_score=False, kwargs={})
2023-11-03 15:18:05,983:INFO:Checking exceptions
2023-11-03 15:18:05,983:INFO:Importing libraries
2023-11-03 15:18:05,983:INFO:Copying training dataset
2023-11-03 15:18:05,986:INFO:Defining folds
2023-11-03 15:18:05,986:INFO:Declaring metric variables
2023-11-03 15:18:05,986:INFO:Importing untrained model
2023-11-03 15:18:05,987:INFO:K Neighbors Classifier Imported successfully
2023-11-03 15:18:05,987:INFO:Starting cross validation
2023-11-03 15:18:05,988:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-03 15:18:06,647:INFO:Calculating mean and std
2023-11-03 15:18:06,648:INFO:Creating metrics dataframe
2023-11-03 15:18:06,651:INFO:Uploading results into container
2023-11-03 15:18:06,651:INFO:Uploading model into container now
2023-11-03 15:18:06,652:INFO:_master_model_container: 2
2023-11-03 15:18:06,652:INFO:_display_container: 2
2023-11-03 15:18:06,652:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2023-11-03 15:18:06,652:INFO:create_model() successfully completed......................................
2023-11-03 15:18:06,711:INFO:SubProcess create_model() end ==================================
2023-11-03 15:18:06,712:INFO:Creating metrics dataframe
2023-11-03 15:18:06,716:INFO:Initializing Naive Bayes
2023-11-03 15:18:06,716:INFO:Total runtime is 0.13253145217895507 minutes
2023-11-03 15:18:06,716:INFO:SubProcess create_model() called ==================================
2023-11-03 15:18:06,717:INFO:Initializing create_model()
2023-11-03 15:18:06,717:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001EF58621690>, estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001EF588AD300>, model_only=True, return_train_score=False, kwargs={})
2023-11-03 15:18:06,717:INFO:Checking exceptions
2023-11-03 15:18:06,717:INFO:Importing libraries
2023-11-03 15:18:06,717:INFO:Copying training dataset
2023-11-03 15:18:06,720:INFO:Defining folds
2023-11-03 15:18:06,720:INFO:Declaring metric variables
2023-11-03 15:18:06,720:INFO:Importing untrained model
2023-11-03 15:18:06,720:INFO:Naive Bayes Imported successfully
2023-11-03 15:18:06,721:INFO:Starting cross validation
2023-11-03 15:18:06,722:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-03 15:18:07,286:INFO:Calculating mean and std
2023-11-03 15:18:07,287:INFO:Creating metrics dataframe
2023-11-03 15:18:07,289:INFO:Uploading results into container
2023-11-03 15:18:07,290:INFO:Uploading model into container now
2023-11-03 15:18:07,290:INFO:_master_model_container: 3
2023-11-03 15:18:07,290:INFO:_display_container: 2
2023-11-03 15:18:07,290:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2023-11-03 15:18:07,290:INFO:create_model() successfully completed......................................
2023-11-03 15:18:07,338:INFO:SubProcess create_model() end ==================================
2023-11-03 15:18:07,338:INFO:Creating metrics dataframe
2023-11-03 15:18:07,342:INFO:Initializing Decision Tree Classifier
2023-11-03 15:18:07,342:INFO:Total runtime is 0.14296552737553914 minutes
2023-11-03 15:18:07,342:INFO:SubProcess create_model() called ==================================
2023-11-03 15:18:07,342:INFO:Initializing create_model()
2023-11-03 15:18:07,342:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001EF58621690>, estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001EF588AD300>, model_only=True, return_train_score=False, kwargs={})
2023-11-03 15:18:07,342:INFO:Checking exceptions
2023-11-03 15:18:07,342:INFO:Importing libraries
2023-11-03 15:18:07,342:INFO:Copying training dataset
2023-11-03 15:18:07,345:INFO:Defining folds
2023-11-03 15:18:07,345:INFO:Declaring metric variables
2023-11-03 15:18:07,345:INFO:Importing untrained model
2023-11-03 15:18:07,346:INFO:Decision Tree Classifier Imported successfully
2023-11-03 15:18:07,346:INFO:Starting cross validation
2023-11-03 15:18:07,347:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-03 15:18:07,802:INFO:Calculating mean and std
2023-11-03 15:18:07,802:INFO:Creating metrics dataframe
2023-11-03 15:18:07,805:INFO:Uploading results into container
2023-11-03 15:18:07,806:INFO:Uploading model into container now
2023-11-03 15:18:07,806:INFO:_master_model_container: 4
2023-11-03 15:18:07,806:INFO:_display_container: 2
2023-11-03 15:18:07,806:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=123, splitter='best')
2023-11-03 15:18:07,807:INFO:create_model() successfully completed......................................
2023-11-03 15:18:07,874:INFO:SubProcess create_model() end ==================================
2023-11-03 15:18:07,875:INFO:Creating metrics dataframe
2023-11-03 15:18:07,879:INFO:Initializing SVM - Linear Kernel
2023-11-03 15:18:07,879:INFO:Total runtime is 0.15191836754480997 minutes
2023-11-03 15:18:07,879:INFO:SubProcess create_model() called ==================================
2023-11-03 15:18:07,880:INFO:Initializing create_model()
2023-11-03 15:18:07,880:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001EF58621690>, estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001EF588AD300>, model_only=True, return_train_score=False, kwargs={})
2023-11-03 15:18:07,880:INFO:Checking exceptions
2023-11-03 15:18:07,880:INFO:Importing libraries
2023-11-03 15:18:07,880:INFO:Copying training dataset
2023-11-03 15:18:07,883:INFO:Defining folds
2023-11-03 15:18:07,883:INFO:Declaring metric variables
2023-11-03 15:18:07,883:INFO:Importing untrained model
2023-11-03 15:18:07,883:INFO:SVM - Linear Kernel Imported successfully
2023-11-03 15:18:07,884:INFO:Starting cross validation
2023-11-03 15:18:07,885:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-03 15:18:08,211:WARNING:C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-03 15:18:08,211:WARNING:C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-03 15:18:08,211:WARNING:C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-03 15:18:08,211:WARNING:C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-03 15:18:08,211:WARNING:C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-03 15:18:08,211:WARNING:C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-03 15:18:08,343:WARNING:C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-03 15:18:08,348:WARNING:C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-03 15:18:08,352:INFO:Calculating mean and std
2023-11-03 15:18:08,353:INFO:Creating metrics dataframe
2023-11-03 15:18:08,355:INFO:Uploading results into container
2023-11-03 15:18:08,356:INFO:Uploading model into container now
2023-11-03 15:18:08,356:INFO:_master_model_container: 5
2023-11-03 15:18:08,356:INFO:_display_container: 2
2023-11-03 15:18:08,356:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=123, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2023-11-03 15:18:08,356:INFO:create_model() successfully completed......................................
2023-11-03 15:18:08,403:INFO:SubProcess create_model() end ==================================
2023-11-03 15:18:08,403:INFO:Creating metrics dataframe
2023-11-03 15:18:08,407:INFO:Initializing Ridge Classifier
2023-11-03 15:18:08,407:INFO:Total runtime is 0.16071170568466187 minutes
2023-11-03 15:18:08,407:INFO:SubProcess create_model() called ==================================
2023-11-03 15:18:08,407:INFO:Initializing create_model()
2023-11-03 15:18:08,407:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001EF58621690>, estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001EF588AD300>, model_only=True, return_train_score=False, kwargs={})
2023-11-03 15:18:08,407:INFO:Checking exceptions
2023-11-03 15:18:08,407:INFO:Importing libraries
2023-11-03 15:18:08,407:INFO:Copying training dataset
2023-11-03 15:18:08,410:INFO:Defining folds
2023-11-03 15:18:08,410:INFO:Declaring metric variables
2023-11-03 15:18:08,410:INFO:Importing untrained model
2023-11-03 15:18:08,410:INFO:Ridge Classifier Imported successfully
2023-11-03 15:18:08,410:INFO:Starting cross validation
2023-11-03 15:18:08,412:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-03 15:18:08,688:WARNING:C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-03 15:18:08,689:WARNING:C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-03 15:18:08,690:WARNING:C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-03 15:18:08,692:WARNING:C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-03 15:18:08,692:WARNING:C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-03 15:18:08,693:WARNING:C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-03 15:18:08,694:WARNING:C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-03 15:18:08,729:WARNING:C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-03 15:18:08,860:WARNING:C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-03 15:18:08,867:WARNING:C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-03 15:18:08,871:INFO:Calculating mean and std
2023-11-03 15:18:08,872:INFO:Creating metrics dataframe
2023-11-03 15:18:08,874:INFO:Uploading results into container
2023-11-03 15:18:08,875:INFO:Uploading model into container now
2023-11-03 15:18:08,875:INFO:_master_model_container: 6
2023-11-03 15:18:08,875:INFO:_display_container: 2
2023-11-03 15:18:08,875:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=123, solver='auto',
                tol=0.0001)
2023-11-03 15:18:08,875:INFO:create_model() successfully completed......................................
2023-11-03 15:18:08,923:INFO:SubProcess create_model() end ==================================
2023-11-03 15:18:08,923:INFO:Creating metrics dataframe
2023-11-03 15:18:08,927:INFO:Initializing Random Forest Classifier
2023-11-03 15:18:08,927:INFO:Total runtime is 0.16937114397684733 minutes
2023-11-03 15:18:08,927:INFO:SubProcess create_model() called ==================================
2023-11-03 15:18:08,927:INFO:Initializing create_model()
2023-11-03 15:18:08,927:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001EF58621690>, estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001EF588AD300>, model_only=True, return_train_score=False, kwargs={})
2023-11-03 15:18:08,927:INFO:Checking exceptions
2023-11-03 15:18:08,927:INFO:Importing libraries
2023-11-03 15:18:08,927:INFO:Copying training dataset
2023-11-03 15:18:08,930:INFO:Defining folds
2023-11-03 15:18:08,931:INFO:Declaring metric variables
2023-11-03 15:18:08,931:INFO:Importing untrained model
2023-11-03 15:18:08,931:INFO:Random Forest Classifier Imported successfully
2023-11-03 15:18:08,931:INFO:Starting cross validation
2023-11-03 15:18:08,932:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-03 15:18:10,030:INFO:Calculating mean and std
2023-11-03 15:18:10,031:INFO:Creating metrics dataframe
2023-11-03 15:18:10,034:INFO:Uploading results into container
2023-11-03 15:18:10,034:INFO:Uploading model into container now
2023-11-03 15:18:10,035:INFO:_master_model_container: 7
2023-11-03 15:18:10,035:INFO:_display_container: 2
2023-11-03 15:18:10,035:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=123, verbose=0, warm_start=False)
2023-11-03 15:18:10,035:INFO:create_model() successfully completed......................................
2023-11-03 15:18:10,088:INFO:SubProcess create_model() end ==================================
2023-11-03 15:18:10,089:INFO:Creating metrics dataframe
2023-11-03 15:18:10,092:INFO:Initializing Quadratic Discriminant Analysis
2023-11-03 15:18:10,092:INFO:Total runtime is 0.1887960950533549 minutes
2023-11-03 15:18:10,092:INFO:SubProcess create_model() called ==================================
2023-11-03 15:18:10,093:INFO:Initializing create_model()
2023-11-03 15:18:10,093:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001EF58621690>, estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001EF588AD300>, model_only=True, return_train_score=False, kwargs={})
2023-11-03 15:18:10,093:INFO:Checking exceptions
2023-11-03 15:18:10,093:INFO:Importing libraries
2023-11-03 15:18:10,093:INFO:Copying training dataset
2023-11-03 15:18:10,096:INFO:Defining folds
2023-11-03 15:18:10,096:INFO:Declaring metric variables
2023-11-03 15:18:10,096:INFO:Importing untrained model
2023-11-03 15:18:10,096:INFO:Quadratic Discriminant Analysis Imported successfully
2023-11-03 15:18:10,096:INFO:Starting cross validation
2023-11-03 15:18:10,098:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-03 15:18:10,314:WARNING:C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-11-03 15:18:10,314:WARNING:C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-11-03 15:18:10,314:WARNING:C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-11-03 15:18:10,314:WARNING:C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-11-03 15:18:10,314:WARNING:C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-11-03 15:18:10,314:WARNING:C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-11-03 15:18:10,314:WARNING:C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-11-03 15:18:10,501:WARNING:C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-11-03 15:18:10,503:WARNING:C:\Users\duart\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-11-03 15:18:10,552:INFO:Calculating mean and std
2023-11-03 15:18:10,553:INFO:Creating metrics dataframe
2023-11-03 15:18:10,555:INFO:Uploading results into container
2023-11-03 15:18:10,556:INFO:Uploading model into container now
2023-11-03 15:18:10,556:INFO:_master_model_container: 8
2023-11-03 15:18:10,556:INFO:_display_container: 2
2023-11-03 15:18:10,556:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2023-11-03 15:18:10,556:INFO:create_model() successfully completed......................................
2023-11-03 15:18:10,603:INFO:SubProcess create_model() end ==================================
2023-11-03 15:18:10,603:INFO:Creating metrics dataframe
2023-11-03 15:18:10,606:INFO:Initializing Ada Boost Classifier
2023-11-03 15:18:10,606:INFO:Total runtime is 0.19735658963521321 minutes
2023-11-03 15:18:10,607:INFO:SubProcess create_model() called ==================================
2023-11-03 15:18:10,607:INFO:Initializing create_model()
2023-11-03 15:18:10,607:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001EF58621690>, estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001EF588AD300>, model_only=True, return_train_score=False, kwargs={})
2023-11-03 15:18:10,607:INFO:Checking exceptions
2023-11-03 15:18:10,607:INFO:Importing libraries
2023-11-03 15:18:10,607:INFO:Copying training dataset
2023-11-03 15:18:10,610:INFO:Defining folds
2023-11-03 15:18:10,610:INFO:Declaring metric variables
2023-11-03 15:18:10,610:INFO:Importing untrained model
2023-11-03 15:18:10,610:INFO:Ada Boost Classifier Imported successfully
2023-11-03 15:18:10,610:INFO:Starting cross validation
2023-11-03 15:18:10,612:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-03 15:18:11,039:INFO:Calculating mean and std
2023-11-03 15:18:11,040:INFO:Creating metrics dataframe
2023-11-03 15:18:11,042:INFO:Uploading results into container
2023-11-03 15:18:11,043:INFO:Uploading model into container now
2023-11-03 15:18:11,043:INFO:_master_model_container: 9
2023-11-03 15:18:11,043:INFO:_display_container: 2
2023-11-03 15:18:11,043:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=123)
2023-11-03 15:18:11,043:INFO:create_model() successfully completed......................................
2023-11-03 15:18:11,091:INFO:SubProcess create_model() end ==================================
2023-11-03 15:18:11,091:INFO:Creating metrics dataframe
2023-11-03 15:18:11,094:INFO:Initializing Gradient Boosting Classifier
2023-11-03 15:18:11,095:INFO:Total runtime is 0.20550982554753622 minutes
2023-11-03 15:18:11,095:INFO:SubProcess create_model() called ==================================
2023-11-03 15:18:11,095:INFO:Initializing create_model()
2023-11-03 15:18:11,095:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001EF58621690>, estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001EF588AD300>, model_only=True, return_train_score=False, kwargs={})
2023-11-03 15:18:11,095:INFO:Checking exceptions
2023-11-03 15:18:11,095:INFO:Importing libraries
2023-11-03 15:18:11,095:INFO:Copying training dataset
2023-11-03 15:18:11,098:INFO:Defining folds
2023-11-03 15:18:11,098:INFO:Declaring metric variables
2023-11-03 15:18:11,099:INFO:Importing untrained model
2023-11-03 15:18:11,099:INFO:Gradient Boosting Classifier Imported successfully
2023-11-03 15:18:11,099:INFO:Starting cross validation
2023-11-03 15:18:11,100:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-03 15:18:11,812:INFO:Calculating mean and std
2023-11-03 15:18:11,813:INFO:Creating metrics dataframe
2023-11-03 15:18:11,815:INFO:Uploading results into container
2023-11-03 15:18:11,815:INFO:Uploading model into container now
2023-11-03 15:18:11,816:INFO:_master_model_container: 10
2023-11-03 15:18:11,816:INFO:_display_container: 2
2023-11-03 15:18:11,816:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=123, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-11-03 15:18:11,816:INFO:create_model() successfully completed......................................
2023-11-03 15:18:11,862:INFO:SubProcess create_model() end ==================================
2023-11-03 15:18:11,862:INFO:Creating metrics dataframe
2023-11-03 15:18:11,865:INFO:Initializing Linear Discriminant Analysis
2023-11-03 15:18:11,865:INFO:Total runtime is 0.2183398445447286 minutes
2023-11-03 15:18:11,865:INFO:SubProcess create_model() called ==================================
2023-11-03 15:18:11,866:INFO:Initializing create_model()
2023-11-03 15:18:11,866:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001EF58621690>, estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001EF588AD300>, model_only=True, return_train_score=False, kwargs={})
2023-11-03 15:18:11,866:INFO:Checking exceptions
2023-11-03 15:18:11,866:INFO:Importing libraries
2023-11-03 15:18:11,866:INFO:Copying training dataset
2023-11-03 15:18:11,868:INFO:Defining folds
2023-11-03 15:18:11,868:INFO:Declaring metric variables
2023-11-03 15:18:11,869:INFO:Importing untrained model
2023-11-03 15:18:11,869:INFO:Linear Discriminant Analysis Imported successfully
2023-11-03 15:18:11,869:INFO:Starting cross validation
2023-11-03 15:18:11,870:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-03 15:18:12,291:INFO:Calculating mean and std
2023-11-03 15:18:12,292:INFO:Creating metrics dataframe
2023-11-03 15:18:12,294:INFO:Uploading results into container
2023-11-03 15:18:12,295:INFO:Uploading model into container now
2023-11-03 15:18:12,295:INFO:_master_model_container: 11
2023-11-03 15:18:12,295:INFO:_display_container: 2
2023-11-03 15:18:12,295:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2023-11-03 15:18:12,295:INFO:create_model() successfully completed......................................
2023-11-03 15:18:12,340:INFO:SubProcess create_model() end ==================================
2023-11-03 15:18:12,341:INFO:Creating metrics dataframe
2023-11-03 15:18:12,344:INFO:Initializing Extra Trees Classifier
2023-11-03 15:18:12,344:INFO:Total runtime is 0.22632262309392293 minutes
2023-11-03 15:18:12,344:INFO:SubProcess create_model() called ==================================
2023-11-03 15:18:12,344:INFO:Initializing create_model()
2023-11-03 15:18:12,344:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001EF58621690>, estimator=et, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001EF588AD300>, model_only=True, return_train_score=False, kwargs={})
2023-11-03 15:18:12,344:INFO:Checking exceptions
2023-11-03 15:18:12,344:INFO:Importing libraries
2023-11-03 15:18:12,344:INFO:Copying training dataset
2023-11-03 15:18:12,348:INFO:Defining folds
2023-11-03 15:18:12,348:INFO:Declaring metric variables
2023-11-03 15:18:12,348:INFO:Importing untrained model
2023-11-03 15:18:12,348:INFO:Extra Trees Classifier Imported successfully
2023-11-03 15:18:12,349:INFO:Starting cross validation
2023-11-03 15:18:12,350:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-03 15:18:13,417:INFO:Calculating mean and std
2023-11-03 15:18:13,418:INFO:Creating metrics dataframe
2023-11-03 15:18:13,420:INFO:Uploading results into container
2023-11-03 15:18:13,421:INFO:Uploading model into container now
2023-11-03 15:18:13,421:INFO:_master_model_container: 12
2023-11-03 15:18:13,421:INFO:_display_container: 2
2023-11-03 15:18:13,422:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=123, verbose=0, warm_start=False)
2023-11-03 15:18:13,422:INFO:create_model() successfully completed......................................
2023-11-03 15:18:13,474:INFO:SubProcess create_model() end ==================================
2023-11-03 15:18:13,474:INFO:Creating metrics dataframe
2023-11-03 15:18:13,478:INFO:Initializing Light Gradient Boosting Machine
2023-11-03 15:18:13,478:INFO:Total runtime is 0.2452248454093933 minutes
2023-11-03 15:18:13,478:INFO:SubProcess create_model() called ==================================
2023-11-03 15:18:13,478:INFO:Initializing create_model()
2023-11-03 15:18:13,478:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001EF58621690>, estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001EF588AD300>, model_only=True, return_train_score=False, kwargs={})
2023-11-03 15:18:13,478:INFO:Checking exceptions
2023-11-03 15:18:13,478:INFO:Importing libraries
2023-11-03 15:18:13,478:INFO:Copying training dataset
2023-11-03 15:18:13,481:INFO:Defining folds
2023-11-03 15:18:13,481:INFO:Declaring metric variables
2023-11-03 15:18:13,481:INFO:Importing untrained model
2023-11-03 15:18:13,481:INFO:Light Gradient Boosting Machine Imported successfully
2023-11-03 15:18:13,482:INFO:Starting cross validation
2023-11-03 15:18:13,483:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-03 15:18:14,362:INFO:Calculating mean and std
2023-11-03 15:18:14,362:INFO:Creating metrics dataframe
2023-11-03 15:18:14,367:INFO:Uploading results into container
2023-11-03 15:18:14,367:INFO:Uploading model into container now
2023-11-03 15:18:14,368:INFO:_master_model_container: 13
2023-11-03 15:18:14,368:INFO:_display_container: 2
2023-11-03 15:18:14,368:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=123, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)
2023-11-03 15:18:14,368:INFO:create_model() successfully completed......................................
2023-11-03 15:18:14,454:INFO:SubProcess create_model() end ==================================
2023-11-03 15:18:14,454:INFO:Creating metrics dataframe
2023-11-03 15:18:14,460:INFO:Initializing Dummy Classifier
2023-11-03 15:18:14,460:INFO:Total runtime is 0.2615950306256612 minutes
2023-11-03 15:18:14,460:INFO:SubProcess create_model() called ==================================
2023-11-03 15:18:14,460:INFO:Initializing create_model()
2023-11-03 15:18:14,460:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001EF58621690>, estimator=dummy, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001EF588AD300>, model_only=True, return_train_score=False, kwargs={})
2023-11-03 15:18:14,460:INFO:Checking exceptions
2023-11-03 15:18:14,460:INFO:Importing libraries
2023-11-03 15:18:14,461:INFO:Copying training dataset
2023-11-03 15:18:14,464:INFO:Defining folds
2023-11-03 15:18:14,464:INFO:Declaring metric variables
2023-11-03 15:18:14,464:INFO:Importing untrained model
2023-11-03 15:18:14,465:INFO:Dummy Classifier Imported successfully
2023-11-03 15:18:14,465:INFO:Starting cross validation
2023-11-03 15:18:14,466:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-03 15:18:14,948:INFO:Calculating mean and std
2023-11-03 15:18:14,948:INFO:Creating metrics dataframe
2023-11-03 15:18:14,951:INFO:Uploading results into container
2023-11-03 15:18:14,951:INFO:Uploading model into container now
2023-11-03 15:18:14,952:INFO:_master_model_container: 14
2023-11-03 15:18:14,952:INFO:_display_container: 2
2023-11-03 15:18:14,952:INFO:DummyClassifier(constant=None, random_state=123, strategy='prior')
2023-11-03 15:18:14,952:INFO:create_model() successfully completed......................................
2023-11-03 15:18:15,004:INFO:SubProcess create_model() end ==================================
2023-11-03 15:18:15,004:INFO:Creating metrics dataframe
2023-11-03 15:18:15,009:INFO:Initializing create_model()
2023-11-03 15:18:15,009:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001EF58621690>, estimator=DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=123, splitter='best'), fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, kwargs={})
2023-11-03 15:18:15,010:INFO:Checking exceptions
2023-11-03 15:18:15,010:INFO:Importing libraries
2023-11-03 15:18:15,010:INFO:Copying training dataset
2023-11-03 15:18:15,013:INFO:Defining folds
2023-11-03 15:18:15,013:INFO:Declaring metric variables
2023-11-03 15:18:15,014:INFO:Importing untrained model
2023-11-03 15:18:15,014:INFO:Declaring custom model
2023-11-03 15:18:15,014:INFO:Decision Tree Classifier Imported successfully
2023-11-03 15:18:15,015:INFO:Cross validation set to False
2023-11-03 15:18:15,015:INFO:Fitting Model
2023-11-03 15:18:15,104:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=123, splitter='best')
2023-11-03 15:18:15,104:INFO:create_model() successfully completed......................................
2023-11-03 15:18:15,169:INFO:_master_model_container: 14
2023-11-03 15:18:15,169:INFO:_display_container: 2
2023-11-03 15:18:15,169:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=123, splitter='best')
2023-11-03 15:18:15,170:INFO:compare_models() successfully completed......................................
